allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - hono@4.12.24
  - '@biomejs/biome@2.5.0'
  - '@biomejs/cli-darwin-arm64@2.5.0'
  - '@biomejs/cli-darwin-x64@2.5.0'
  - '@biomejs/cli-linux-arm64-musl@2.5.0'
  - '@biomejs/cli-linux-arm64@2.5.0'
  - '@biomejs/cli-linux-x64-musl@2.5.0'
  - '@biomejs/cli-linux-x64@2.5.0'
  - '@biomejs/cli-win32-arm64@2.5.0'
  - '@biomejs/cli-win32-x64@2.5.0'
  - miniflare@4.20260611.0
  - wrangler@4.100.0
